[package]
name = "control-board"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.8.0"
clap = "3.1.18"
paudio = { version = "0.3.2", package = "pulsectl-rs" }
config = "0.13.1"
serde = "1.0.39"
home = "0.5.3"
